version: 2.1

orbs:
  node: circleci/node@5.0.0

workflows:
  test:
    jobs:
      - node/test:
          setup:
            # derive cache key from package.json
            - run: cp package.json package-lock.json
          override-ci-command: rm package-lock.json && npm install && git checkout -- package.json
          matrix:
            parameters:
              version:
                - 10.14.2
                - 12.0.0
                - 14.0.0
                - 16.0.0
